[package]
name = "ziplocator_ui"
version = "0.1.0"
edition = "2021"

[dependencies]
ziplocator_nn.workspace = true
galileo.workspace = true
iced.workspace = true
pollster.workspace = true
tokio.workspace = true
